### ISSUE TITLE
Remove `rsync` and use native nodejs against cross-platform compatibility issues

### ISSUE THREAD

**Issue by Stradivario** [rxdi/firelink#11]

**Comment by Stradivario** [comment]
Testing out the library on windows is giving error that `rsync` is missing this is a top priority to be fixed!

```bash
PS C:\Users\Rampage\Downloads\test> .\firelink-win.exe
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn rsync ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn rsync',
  path: 'rsync',
  spawnargs: [
    '-r',
    '--exclude',
    'node_modules',
    '--exclude',
    'dist',
    '--exclude',
    '.cache',
    './packages/dependency',
    './.packages'
  ]
}
```

**Comment by Stradivario** [comment]
Created PR to fix cross compatibility issues https://github.com/rxdi/firelink/pull/23
